################### OHMYZSH ###############
export ZSH="$HOME/.oh-my-zsh"
# ZSH_THEME=""
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=()
source $ZSH/oh-my-zsh.sh
##################### POWERLEVEL10k #########
# THEME
# POWERLEVEL9K_COLOR_SCHEME=''
# ELEMENT
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user host dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs time)
# SEGMENT LEFT
POWERLEVEL9K_USER_BACKGROUND='203'
POWERLEVEL9K_USER_FOREGROUND='015'
POWERLEVEL9K_HOST_BACKGROUND='254'
POWERLEVEL9K_HOST_FOREGROUND='black'
POWERLEVEL9K_DIR_BACKGROUND='111'
POWERLEVEL9K_DIR_FOREGROUND='black'
POWERLEVEL9K_VCS_BACKGROUND='079'
POWERLEVEL9K_VCS_FOREGROUND='black'
# SEGMENT RIGHT
POWERLEVEL9K_TIME_BACKGROUND='203'
POWERLEVEL9K_TIME_FOREGROUND='015'
# POWERLEVEL9K_BATTERY_BACKGROUND='254'
# POWERLEVEL9K_BATTERY_FOREGROUND='black'
################# CACHE REMOVE ##############
rm -f ~/.zcompdump*